### ISSUE TITLE
Whether or not Admin approval is required when creating an event

### ISSUE THREAD

**Issue by ngnlyoosun** [pacemakerIT/Gachi#12]
Should events submitted by mentors be displayed on the site immediately, or should they first go through an evaluation and approval process by an administrator to ensure their appropriateness before being published?

Ralph said he wanted communication and networking to flow smoothly between people without him, but if every event required admin approval, Ralph would have a lot to worry about.

**Comment by nhistory** [comment]
회의에서 논의하고 이슈 닫음
