### ISSUE TITLE
Coding convention 리서치 및 결정

### ISSUE THREAD

**Issue by nhistory** [pacemakerIT/Gachi#15]
- TypeScript 와 관련된 convension
  - [Airbnb JavaScript style guide](https://airbnb.io/javascript/react/#naming)
  - [Google TypeScript style guide](https://google.github.io/styleguide/tsguide.html#imports)
- Nextjs + MUI 과 관련된 convension
  - [example repository](https://github.com/mui/material-ui/tree/master/examples/material-ui-nextjs-ts)
  - 프로젝트 폴더 구성

**Comment by mirimkim00** [comment]
https://github.com/airbnb/javascript?tab=readme-ov-file

https://nextjs.org/docs/app/api-reference/file-conventions

https://medium.com/@mirazhs/naming-conventions-in-next-js-boosting-seo-and-code-maintainability-d4150fe7e6e

**Comment by nhistory** [comment]
File, Folder name -> Kebab case
ex) pro-tip.tsx

**Comment by nhistory** [comment]
string format : single quote (')

**Comment by nhistory** [comment]
https://marketplace.visualstudio.com/items?itemName=Blackboxapp.blackbox

**Comment by mirimkim00** [comment]
Component : Pascal case (ProTip)
