### ISSUE TITLE
Design Templates

### ISSUE THREAD

**Issue by nhistory** [pacemakerIT/Gachi#7]
Mirim
https://www.figma.com/design/sIqIR9KUYDcqnHzNJdsSl2/Yodora---Landing-Page-Design-%7C-Freebies-by-%40itsrehanraihan-(Community)?node-id=0-1&node-type=CANVAS&t=j093bTUSGZHbUH1q-0

https://www.figma.com/design/ZjWI70V0DzlIS9j7n4liqx/Comforty---eCommerce-Figma-Template-(Community)-(Community)?node-id=0-1&node-type=CANVAS&t=3ujOW1QKjTT8laGh-0

https://dribbble.com/shots/22712725-AI-SaaS-landing-page-design

Yoo Sun Song
Animation 효과가 좋음
https://www.figma.com/community/file/778961842657921355

https://dribbble.com/shots/21939083-Travel-agency-Landing-page

1. The template allows for the incorporation of a variety of animation effects, enhancing the overall user experience.
2. The card section enables us to promote events through preview displays, making the content more engaging.
3. The light blue color scheme aligns well with the image and branding of an educational platform.

https://dribbble.com/shots/22204035-Travel-Website-UI

1. The template has a simple and modern design, which contributes to a clean aesthetic.
2. It is user-friendly and easy for visitors to navigate, ensuring a comfortable user experience.
3. Its minimalist approach gives it a neat and uncluttered look, enhancing visual clarity.

https://www.gdweb.co.kr/sub/view.asp?displayrow=60&Txt_key=all&Txt_word&Txt_agnumber&Txt_fgbn=5&Txt_bcode1=021510001&Txt_gbflag&Txt_bcode2&Txt_bcode3&Txt_bcode4&Txt_bcode5&Page=1&str_no=18019

1. The design makes it easy for users to quickly understand the purpose of the site.
2. It provides a clear structure, making it simple to summarize what the site is about.
3. Its clean and minimalist layout enhances the overall clarity and user experience.

**Comment by DerpyTheSpy** [comment]
Simple and easy to read : [SaaS Landing Page Template](https://www.figma.com/design/BIbEiRel3iFXHEqcMSPUR3/SaaS-Landing-Page-Template---Landing-Page-Template-ready-to-export-to-HTML---Landing-page-for-SaaS-(Community)?node-id=0-1&node-type=CANVAS&t=zJhwlDNpWgIMpMV8-0)



Well Organized and easy to look at : [Template 2](https://www.figma.com/design/SWeLJzjYHfOlBRmoXI3RqY/Responsive%2FComponents-Landing-Page---Construction-Company-(Community)?node-id=0-1&node-type=CANVAS&t=cprttc2uQei60qRT-0)

Highly recommended one : [Template 3](https://www.figma.com/design/zrAauNU8d8j7M4G7S8ocqO/healthcare-landing-page-with-full-website-pages-(Community)?m=auto&is-community-duplicate=1&fuid=1411506456713471658)

**Comment by mirimkim00** [comment]
Edit 버튼이 사라져서 코멘트로 특징 정리해놓은 메모 추가합니다!

1. [Figma- Yodora](https://www.figma.com/design/sIqIR9KUYDcqnHzNJdsSl2/Yodora---Landing-Page-Design-%7C-Freebies-by-%40itsrehanraihan-(Community)?node-id=0-1&node-type=CANVAS&t=j093bTUSGZHbUH1q-0)
    1. 모바일 디자인도 있음
    2. hero의 텍스트 부분이나 그 밑에 화면부분에 스케치 영상 움짤 등 스크롤 효과 넣을수도 있을거같음
    3. 사람 사진 있는 부분에 최신등록/인기/마감임박 등의 모임/세미나/이벤트 carousel로 뜨게 해도 괜찮을것 같음
    4. -약간 수정 많이 필요할수도
2. [Comfort](https://www.figma.com/design/ZjWI70V0DzlIS9j7n4liqx/Comforty---eCommerce-Figma-Template-(Community)-(Community)?node-id=0-1&node-type=CANVAS&t=3ujOW1QKjTT8laGh-0)
    1. 가구사진만 바꾸면 ui가 괜찮은거 같아보여서 선정
    2. -스크롤 어떻게 적용할지 아이디어 없음
3. [AI Saas](https://dribbble.com/shots/22712725-AI-SaaS-landing-page-design)
    1. hero 애니메이션 디자인 참고

**Comment by nhistory** [comment]
@mirimkim00 오른쪽 위 점 3개 아이콘 클릭하면 edit 할 수 있습니다.

![image](https://github.com/user-attachments/assets/75372129-494b-4675-8e2b-da47aaf57209)

**Comment by mirimkim00** [comment]
@nhistory 
저는 이렇게 보입니다ㅜㅜ 아까 미팅중에는 edit 버튼이 있었는데 지금은 안보이더라구요..

![Image](https://github.com/user-attachments/assets/ad866588-3c1e-44a3-a526-208379048dd4)

**Comment by nhistory** [comment]
@mirimkim00 제가 프로젝트에 쓰기 권한 드리는 걸 빼먹었네요 ㅜ
지금 한번 확인해보시겠어요?

**Comment by mirimkim00** [comment]
@nhistory 지금도 저 스크린샷이랑 똑같이 보여요ㅜㅜ

**Comment by nhistory** [comment]
@mirimkim00 프로젝트 레파지토리에 쓰기권한도 추가했는데 edit 버튼 활성화 되었는지 시간 나실 때 한번 확인 부탁드립니다.

**Comment by mirimkim00** [comment]
@nhistory 이제 보여요! 감사합니다!!
