### ISSUE TITLE
Functional Requirements

### ISSUE THREAD

**Issue by nhistory** [pacemakerIT/Gachi#9]

**Comment by DerpyTheSpy** [comment]
[Google Doc Link to Functional Requirements](https://docs.google.com/document/d/1ZqGdDnYlKY_qfH_GAsYXvyEjMbMUMOx_OroudifA2Po/edit?usp=sharing)

**Comment by ngnlyoosun** [comment]
- FR1: User Registration & Profile management
- FR2: Event Management
- FR3: Mentor Matching and Interaction
- FR4: Feedback and Review System
- FR5: User Authentication
- FR6: Admin Dashboard
